/**
 * PersonBrief colour tokens, mirrored from the website (src/app/globals.css).
 * The mobile app styles native views with these values; a unit test keeps
 * both copies identical, so change brand colours in both places together.
 */

export const COLOR_TOKENS = [
  "canvas",
  "surface",
  "surface-2",
  "surface-sunken",
  "ink",
  "ink-2",
  "muted",
  "subtle",
  "line",
  "line-strong",
  "accent",
  "accent-hover",
  "accent-soft",
  "accent-ink",
  "on-accent",
  "focus",
  "ok",
  "ok-soft",
  "warn",
  "warn-soft",
  "danger",
  "danger-soft",
  "violet",
  "violet-soft",
  "slate-soft",
  "demo",
  "demo-soft",
  "demo-line",
] as const;
export type ColorToken = (typeof COLOR_TOKENS)[number];
export type Palette = Record<ColorToken, string>;

export const LIGHT: Palette = {
  canvas: "#f6f4ee",
  surface: "#ffffff",
  "surface-2": "#faf9f5",
  "surface-sunken": "#efece4",
  ink: "#141b2b",
  "ink-2": "#2b3445",
  muted: "#5d6676",
  subtle: "#666e7c",
  line: "#e4dfd3",
  "line-strong": "#cfc8b8",
  accent: "#2c56c9",
  "accent-hover": "#2348ad",
  "accent-soft": "#e8eefb",
  "accent-ink": "#1d3f99",
  "on-accent": "#ffffff",
  focus: "#2c56c9",
  ok: "#2a7046",
  "ok-soft": "#e6f2ea",
  warn: "#8a5a10",
  "warn-soft": "#fbf0d9",
  danger: "#b03a2e",
  "danger-soft": "#f8e6e3",
  violet: "#6b4fa0",
  "violet-soft": "#efeaf7",
  "slate-soft": "#eef0f3",
  demo: "#7a4b00",
  "demo-soft": "#fff1d6",
  "demo-line": "#f0d29a",
};

export const DARK: Palette = {
  canvas: "#0e121a",
  surface: "#151b26",
  "surface-2": "#19202c",
  "surface-sunken": "#0b0f16",
  ink: "#e8ebf1",
  "ink-2": "#cfd5df",
  muted: "#9aa3b2",
  subtle: "#858e9e",
  line: "#262f3e",
  "line-strong": "#364153",
  accent: "#7c9dff",
  "accent-hover": "#9bb4ff",
  "accent-soft": "#1b2744",
  "accent-ink": "#a9bfff",
  "on-accent": "#0b1226",
  focus: "#8fadff",
  ok: "#6cc08f",
  "ok-soft": "#13291d",
  warn: "#e0ad55",
  "warn-soft": "#2d2312",
  danger: "#f08a7e",
  "danger-soft": "#331a17",
  violet: "#b9a2ec",
  "violet-soft": "#241c36",
  "slate-soft": "#1d2430",
  demo: "#f1c26c",
  "demo-soft": "#2c210c",
  "demo-line": "#5a4416",
};
