import { z } from "zod";

/**
 * Conventions for /api/v1 (shared by the server and the mobile app):
 *
 * - JSON bodies; timestamps are ISO 8601 strings in UTC ("2026-10-05T09:30:00.000Z").
 *   Partial dates from sources ("2014", "2014-05") stay strings or
 *   {year, month?, day?} objects and are never widened to full dates.
 * - Identifiers are opaque strings (research, profile and snapshot ids are UUIDs).
 * - Errors use one envelope: { error: { code, message, fieldErrors?, retryAfterSeconds? } }.
 * - Lists that can grow return { items, nextCursor }; pass nextCursor back as ?cursor=.
 * - Expensive writes (starting, retrying or refreshing research) require an
 *   Idempotency-Key header; repeating a request with the same key returns the
 *   original result instead of starting new paid research.
 * - Compatibility: v1 only changes additively (new fields, new optional
 *   parameters, new values in "open" vocabularies). Clients ignore unknown
 *   fields. Anything else gets a new version path.
 */

export const API_VERSION = 1 as const;
export const API_BASE_PATH = "/api/v1" as const;
export const IDEMPOTENCY_HEADER = "Idempotency-Key" as const;
/** Sent by the mobile app so the server can ask very old builds to update. */
export const CLIENT_BUILD_HEADER = "X-PersonBrief-Client" as const;

export const isoDateTime = z.iso.datetime();
export const entityId = z.string().min(1).max(128);
export const uuid = z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, "invalid_id");
/** 8–80 URL-safe characters, generated by the client once per user action. */
export const idempotencyKey = z.string().regex(/^[A-Za-z0-9_-]{8,80}$/, "invalid_idempotency_key");

/**
 * A vocabulary that may gain values in later server versions. Known values
 * keep their literal types; unknown ones still parse (older apps show a
 * neutral label instead of failing).
 */
export function openEnum<const T extends readonly [string, ...string[]]>(_values: T) {
  return z.custom<T[number] | (string & {})>((value) => typeof value === "string");
}

export const API_ERROR_CODES = [
  "unauthenticated",
  "forbidden",
  "not_found",
  "invalid_input",
  "invalid_state",
  "rate_limited",
  "live_not_configured",
  "live_not_allowed",
  "idempotency_key_required",
  "unsupported_client",
  "server_error",
] as const;
export type ApiErrorCode = (typeof API_ERROR_CODES)[number];

export const ApiErrorBodySchema = z.object({
  error: z.object({
    code: openEnum(API_ERROR_CODES),
    /** English fallback; apps translate `code` (and field codes) themselves. */
    message: z.string(),
    /** Field name → message code (Errors.fields.* in the message catalogues). */
    fieldErrors: z.record(z.string(), z.string()).optional(),
    retryAfterSeconds: z.number().int().nonnegative().optional(),
  }),
});
export type ApiErrorBody = z.infer<typeof ApiErrorBodySchema>;

export function pageOf<T extends z.ZodType>(item: T) {
  return z.object({ items: z.array(item), nextCursor: z.string().nullable() });
}
export type Page<T> = { items: T[]; nextCursor: string | null };

export const PartialDateSchema = z.object({
  year: z.number().int(),
  month: z.number().int().nullable().optional(),
  day: z.number().int().nullable().optional(),
  approximate: z.boolean().optional(),
});

export const OkSchema = z.object({ ok: z.literal(true) });
