import { Directory, File, Paths } from "expo-file-system";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";
import { ApiError, apiUrl, authHeaders } from "./api";

/**
 * PDF/JSON exports. The file is generated by the server for the signed-in
 * owner, downloaded into a private temporary folder in the app's cache and
 * handed to the system share sheet. iOS returns once the sheet closes, so the
 * file is deleted straight away; Android returns before the receiving app has
 * read it, so it is removed a few minutes later instead (on the next return
 * to the app). The folder is emptied on every launch and on sign-out. Once
 * the user shares a file to another app (Mail, Files, a chat), that copy
 * belongs to that app and is outside PersonBrief's cleanup.
 */

const FOLDER = "personbrief-exports";

function exportDirectory(): Directory {
  return new Directory(Paths.cache, FOLDER);
}

export async function deleteTemporaryExports(): Promise<void> {
  if (Platform.OS === "web") return;
  try {
    const dir = exportDirectory();
    if (dir.exists) dir.delete();
  } catch {
    // Nothing to clean up, or the OS already purged the cache.
  }
}

/** Remove exports older than `maxAgeMs` (folder names start with their creation time). */
export function pruneTemporaryExports(maxAgeMs = 10 * 60_000): void {
  if (Platform.OS === "web") return;
  try {
    const dir = exportDirectory();
    if (!dir.exists) return;
    for (const entry of dir.list()) {
      const created = Number(entry.name.split("-")[0]);
      if (!Number.isFinite(created) || Date.now() - created > maxAgeMs) entry.delete();
    }
  } catch {
    // ignore
  }
}

export type ExportFormat = "pdf" | "json";

export type ExportOutcome = { status: "shared" } | { status: "unavailable" };

/** Download an owner-protected export and open the share sheet. Notes are only included in JSON when asked. */
export async function shareExport(options: {
  profileId: string;
  snapshotId: string | null;
  format: ExportFormat;
  includeNotes?: boolean;
  dialogTitle: string;
  signal?: AbortSignal;
}): Promise<ExportOutcome> {
  const url = apiUrl(`/profiles/${options.profileId}/export`, {
    format: options.format,
    snapshot: options.snapshotId,
    notes: options.format === "json" && options.includeNotes ? "1" : undefined,
  });
  if (Platform.OS === "web") {
    // Web preview only: the browser downloads with its own session cookie.
    window.open(url, "_blank", "noopener");
    return { status: "shared" };
  }
  if (!(await Sharing.isAvailableAsync())) return { status: "unavailable" };

  const dir = exportDirectory();
  if (!dir.exists) dir.create({ intermediates: true, idempotent: true });
  // A random folder per export keeps the server's file name without collisions.
  const target = new Directory(dir, `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`);
  target.create({ idempotent: true });
  let file: File;
  try {
    file = await File.downloadFileAsync(url, target, { headers: { ...(await authHeaders()), Accept: options.format === "pdf" ? "application/pdf" : "application/json" }, signal: options.signal });
  } catch (error) {
    safeDelete(target);
    const message = error instanceof Error ? error.message : String(error);
    if (/401/.test(message)) throw new ApiError("http", "unauthenticated", "Sign in again to export.", 401);
    if (/404/.test(message)) throw new ApiError("http", "not_found", "This profile is no longer available.", 404);
    if (/429/.test(message)) throw new ApiError("http", "rate_limited", "Too many exports. Please wait a minute.", 429);
    throw new ApiError("network", "offline", "The export could not be downloaded.");
  }
  try {
    await Sharing.shareAsync(file.uri, {
      mimeType: options.format === "pdf" ? "application/pdf" : "application/json",
      UTI: options.format === "pdf" ? "com.adobe.pdf" : "public.json",
      dialogTitle: options.dialogTitle,
    });
  } finally {
    if (Platform.OS === "ios") safeDelete(target);
  }
  return { status: "shared" };
}

function safeDelete(dir: Directory) {
  try {
    if (dir.exists) dir.delete();
  } catch {
    // ignore
  }
}
